spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: admin-service
          uri: lb://admin-service/**
          predicates:
            - Path=/static/admin/**
        - id: user-service
          uri: lb://user-service/**
          predicates:
            - Path=/static/user/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  renewalPercentThreshold: 0.85

server:
  port: 17957

